services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanza_app
    restart: always
    working_dir: /app
    expose:
      - '80'
    volumes:
      - ./.env:/app/.env
      - ./storage:/app/storage
    environment:
      SERVER_NAME: relaxin.my.id
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      APP_DEBUG: false
      APP_URL: https://relaxin.my.id
      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel
    depends_on:
      - mysql

  mysql:
    image: mysql:9.7
    container_name: kanza_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    external: true

volumes:
  mysql_data:
